export enum AuthenticationActions {
  TOKEN_SIGNUP = 'token_signup',
  TOTP = 'totp',
  SIGNIN = 'signin',
  SIGNOUT = 'signout',
}

export enum AuthenticationStates {
  GRANTED = 'GRANTED',
  DENIED = 'DENIED',
  DENIED_USER_NOT_FOUND = 'DENIED_USER_NOT_FOUND',
  DENIED_PASSWORD_AND_TOKEN_INVALIDS = 'DENIED_PASSWORD_AND_TOKEN_INVALIDS',
  DENIED_TOKEN_INVALID = 'DENIED_TOKEN_INVALID',
  DENIED_PASSWORD_INVALID = 'DENIED_PASSWORD_INVALID',
  DENIED_NEW_USER_TOKEN_EXPIRED = 'DENIED_NEW_USER_TOKEN_EXPIRED',
  DENIED_MAX_AUTHENTICATION_ATTEMPTS_REACHED = 'DENIED_MAX_AUTHENTICATION_ATTEMPTS_REACHED',
  DENIED_BLOCKED_USER = 'DENIED_BLOCKED_USER',
  DENIED_TOTP_INVALID = 'DENIED_TOTP_INVALID',
  DENIED_NOT_A_NEW_USER = 'DENIED_NOT_A_NEW_USER',
}
