.base-build:
  stage: 'Build'
  image: ${BUILD_IMAGE}
  tags:
    - build
  only:
    - tags
  when: manual
  environment:
    name: build
  variables:
    GIT_STRATEGY: none
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ''
    RELEASE_VERSION: ${CI_COMMIT_REF_NAME}
  services:
    - name: docker:19.03.12-dind
      command: ['--experimental']
  before_script:
    - echo "$INFRA_REGISTRY_PASS" | docker login $INFRA_REGISTRY --username $INFRA_REGISTRY_USER --password-stdin
    - rm -rf $FC_ROOT/fc-docker
    - git clone -b $FC_DOCKER_VERSION --single-branch https://gitlab-ci-token:$CI_JOB_TOKEN@gitlab.dev-franceconnect.fr/france-connect/fc-docker.git $FC_ROOT/fc-docker
  script:
    - cd $FC_ROOT/fc-docker
    - ./build.sh $APP $RELEASE_VERSION
    - echo -e "\e[1;34m$MSG $RELEASE_VERSION\e[0m"

.base-tag-to-prod:
  stage: 'Tag'
  image: ${BUILD_IMAGE}
  tags:
    - build
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_REF_NAME =~ /RC.$/
      when: manual
      allow_failure: false
  variables:
    GIT_STRATEGY: none
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ''
    PATCH_VERSION: 0
    RELEASE_VERSION: $CI_COMMIT_REF_NAME
    DOCKER_CLI_EXPERIMENTAL: enabled
  services:
    - name: docker:19.03.12-dind
      command: ['--experimental']
  before_script:
    - echo "$INFRA_REGISTRY_PASS" | docker login $INFRA_REGISTRY --username $INFRA_REGISTRY_USER --password-stdin
    - PROD_RELEASE_VERSION=${RELEASE_VERSION::-3}.${PATCH_VERSION}
  script:
    - while docker manifest inspect $INFRA_REGISTRY/$DOCKER_IMAGE:$PROD_RELEASE_VERSION; [[ $? -eq 0 ]];
      do PATCH_VERSION=$((PATCH_VERSION+1)); PROD_RELEASE_VERSION=${RELEASE_VERSION::-3}.${PATCH_VERSION}; done
    - export PROD_RELEASE_VERSION
    - docker pull $INFRA_REGISTRY/$DOCKER_IMAGE:$RELEASE_VERSION
    - docker tag $INFRA_REGISTRY/$DOCKER_IMAGE:$RELEASE_VERSION $INFRA_REGISTRY/$DOCKER_IMAGE:$PROD_RELEASE_VERSION
    - docker push $INFRA_REGISTRY/$DOCKER_IMAGE:$PROD_RELEASE_VERSION
    - echo -e "\e[1;34m$MSG $PROD_RELEASE_VERSION\e[0m"
    - >
      curl -s -X POST --header "PRIVATE-TOKEN: $PRIVATE_TOKEN" "https://gitlab.dev-franceconnect.fr/api/v4/projects/${CI_PROJECT_ID}/repository/tags?tag_name=${PROD_RELEASE_VERSION}&ref=${RELEASE_VERSION}"
  environment:
    name: build

FC+/FCA/exploitation/build-image:
  extends: .base-build
  variables:
    APP: exploitation-v2
    MSG: "environments/pa4-integ/group_vars/all/versions.yml\nfc_exploitation_v2_version:$PROD_RELEASE_VERSION\n\nenvironments/nubo12-fca-integ/group_vars/all/versions.yml\nenvironments/nubo12-fca-integ/group_vars/all/versions.yml\nenvironments/nubo01-fca-integ/group_vars/all/versions.yml\nfca_exploitation_version:"

FC+/FCA/exploitation/tag-to-prod-image:
  extends: .base-tag-to-prod
  variables:
    DOCKER_IMAGE: fc-exploitation-v2
    MSG: "environments/pa4-preprod/group_vars/all/versions.yml\nenvironments/pa4-prod/group_vars/all/versions.yml\nfc_exploitation_v2_version:$PROD_RELEASE_VERSION\n\nenvironments/nubo12-fca-prod/group_vars/all/versions.yml\nenvironments/nubo01-fca-prod/group_vars/all/versions.yml\nfca_exploitation_version:"
  needs:
    - job: FC+/FCA/exploitation/build-image

fc-exploitation/build-image:
  extends: .base-build
  variables:
    APP: exploitation
    MSG: "environments/pa4-integ/group_vars/all/versions.yml\nfc_exploitation_version:"

fc-exploitation/tag-to-prod-image:
  extends: .base-tag-to-prod
  variables:
    DOCKER_IMAGE: fc-exploitation
    MSG: "environments/pa4-preprod/group_vars/all/versions.yml\nenvironments/pa4-prod/group_vars/all/versions.yml\nfc_exploitation_version:"
  needs:
    - job: fc-exploitation/build-image

fc-support/build-image:
  extends: .base-build
  variables:
    APP: support
    MSG: "environments/pa4-integ/group_vars/all/versions.yml\nfc_support_version:"

fc-support/tag-to-prod-image:
  extends: .base-tag-to-prod
  variables:
    DOCKER_IMAGE: fc-support
    MSG: "environments/pa4-preprod/group_vars/all/versions.yml\nenvironments/pa4-prod/group_vars/all/versions.yml\nfc_support_version:"
  needs:
    - job: fc-support/build-image

fc-workers/build-image:
  extends: .base-build
  variables:
    APP: workers
    MSG: "environments/pa4-integ/group_vars/all/versions.yml\nfc_workers_version:"

fc-workers/tag-to-prod-image:
  extends: .base-tag-to-prod
  variables:
    DOCKER_IMAGE: fc-workers
    MSG: "environments/pa4-preprod/group_vars/all/versions.yml\nenvironments/pa4-prod/group_vars/all/versions.yml\nfc_workers_version:"
  needs:
    - job: fc-workers/build-image
