export const aggregateProjectTagName = {
  $project: {
    id: 1,
    title: 1,
    name: 1,
    redirect_uris: 1,
    post_logout_redirect_uris: 1,
    site: 1,
    type: 1,
    email: 1,
    IPServerAddressesAndRanges: 1,
    active: 1,
    secretCreatedAt: 1,
    logo: 1,
    createdAt: 1,
    updatedAt: 1,
    secretUpdatedAt: 1,
    updatedBy: 1,
    secretUpdatedBy: 1,
    key: 1,
    credentialFlow: 1,
    url: 1,
    messageToDisplayWhenInactive: 1,
    redirectionTargetWhenInactive: 1,
    display: 1,
    image: 1,
    alt: 1,
    imageFocus: 1,
    eidas: 1,
    emails: 1,
    statusUrl: 1,
    authorizationUrl: 1,
    tokenUrl: 1,
    userInfoUrl: 1,
    clientId: 1,
    client_secret: 1,
    order: 1,
    jwksUrl: 1,
    trustedIdentity: 1,
    specificText: 1,
    mailto: 1,
    output: { $toLower: '$name' },
    signup_id: 1,
  },
};
