import { Schema } from 'mongoose';

export const clientSchema = new Schema({
  key: { type: String, index: true },
  name: String,
  client_secret: String,
  redirect_uris: [String],
  post_logout_redirect_uris: [String],
  credentialsFlow: { type: Boolean, default: false },
  createdAt: { type: Date, default: Date.now },
  secretCreatedAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now },
  updatedBy: String,
  email: String,
  active: { type: Boolean, default: true },
  logo: Schema.Types.Mixed,
  description: String,
  IPServerAddressesAndRanges: [String],
  idClientEmail: String,
  secretKeyPhone: String,
  contacts: [Schema.Types.Mixed],
  editorName: String,
  production_key: String,
  signup_id: String,
  type: String,
  site: [String],
  scopes: [String],
  blacklistByIdentityProviderActivated: { type: Boolean, default: false },
  whitelistByServiceProviderActivated: { type: Boolean, default: false },
  whitelistByIdentityProvider: Object,
});
